# Use Python 3.11 as the base image
FROM python:3.11-bullseye

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Set working directory
WORKDIR /app

# Install system dependencies including texlive-full
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget=1.21-1+deb11u1 \
    git \
    curl \
    ca-certificates \
    build-essential=12.9 \
    libssl-dev \
    zlib1g-dev=1:1.2.11.dfsg-2+deb11u2 \
    libbz2-dev=1.0.8-4 \
    libreadline-dev=8.1-1 \
    libsqlite3-dev \
    libncursesw5-dev=6.2+20201114-2+deb11u2 \
    xz-utils=5.2.5-2.1~deb11u1 \
    tk-dev=8.6.11+1 \
    libxml2-dev \
    libxmlsec1-dev=1.2.31-1 \
    libffi-dev=3.3-6 \
    liblzma-dev=5.2.5-2.1~deb11u1 \
    texlive-full=2020.20210202-3 \
    && rm -rf /var/lib/apt/lists/*


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_SYSTEM_PYTHON=1

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Install Python packages
RUN uv pip install \
    anthropic \
    aider-chat \
    backoff \
    openai \
    matplotlib \
    pypdf \
    pymupdf4llm \
    torch \
    numpy \
    transformers \
    datasets \
    tiktoken \
    wandb \
    tqdm \
    scikit-learn \
    einops 

# Clone and install NPEET with a specific commit
RUN git clone https://github.com/gregversteeg/NPEET.git
WORKDIR /app/NPEET
RUN git checkout 8b0d9485423f74e5eb199324cf362765596538d3 \
    && uv pip install .

# Clone the AI-Scientist repository
WORKDIR /app
RUN git clone https://github.com/neil-vqa/AI-Scientist.git

# Set working directory to AI-Scientist
WORKDIR /app/AI-Scientist
